// <auto-generated />
using System;
using ByteBattlesServer.Microservices.UserProfile.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ByteBattlesServer.Microservices.UserProfile.Infrastructure.Data.Migrations
{
    [DbContext(typeof(UserProfileDbContext))]
    [Migration("20251210105513_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rarity");

                    b.Property<int>("RequiredValue")
                        .HasColumnType("integer")
                        .HasColumnName("required_value");

                    b.Property<int>("RewardExperience")
                        .HasColumnType("integer")
                        .HasColumnName("reward_experience");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("UnlockMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("unlock_message");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_achievements_category");

                    b.HasIndex("Rarity")
                        .HasDatabaseName("ix_achievements_rarity");

                    b.HasIndex("RequiredValue")
                        .HasDatabaseName("ix_achievements_required_value");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_achievements_type");

                    b.ToTable("achievements", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Problems",
                            Description = "Решите свою первую задачу",
                            IconUrl = "/achievements/first-blood.png",
                            IsSecret = false,
                            Name = "Первая кровь",
                            Rarity = "Common",
                            RequiredValue = 1,
                            RewardExperience = 100,
                            Type = "TotalProblemsSolved",
                            UnlockMessage = "Отличный старт! Первая задача решена!"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Problems",
                            Description = "Решите 10 задач",
                            IconUrl = "/achievements/solver.png",
                            IsSecret = false,
                            Name = "Решатель",
                            Rarity = "Common",
                            RequiredValue = 10,
                            RewardExperience = 250,
                            Type = "TotalProblemsSolved"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Battles",
                            Description = "Выиграйте первый баттл",
                            IconUrl = "/achievements/first-victory.png",
                            IsSecret = false,
                            Name = "Первая победа",
                            Rarity = "Common",
                            RequiredValue = 1,
                            RewardExperience = 200,
                            Type = "Wins",
                            UnlockMessage = "Поздравляем с первой победой в баттле!"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Streaks",
                            Description = "Выиграйте 10 баттлов подряд",
                            IconUrl = "/achievements/invincible.png",
                            IsSecret = false,
                            Name = "Непобедимый",
                            Rarity = "Epic",
                            RequiredValue = 10,
                            RewardExperience = 1500,
                            Type = "CurrentStreak"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Problems",
                            Description = "Решите 100 задач",
                            IconUrl = "/achievements/algorithm-master.png",
                            IsSecret = false,
                            Name = "Мастер алгоритмов",
                            Rarity = "Rare",
                            RequiredValue = 100,
                            RewardExperience = 1000,
                            Type = "TotalProblemsSolved"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "Special",
                            Description = "Решите задачу за 10 секунд",
                            IconUrl = "/achievements/code-ninja.png",
                            IsSecret = true,
                            Name = "Ниндзя кода",
                            Rarity = "Legendary",
                            RequiredValue = 10,
                            RewardExperience = 2000,
                            Type = "FastestSubmission",
                            UnlockMessage = "Невероятная скорость! Вы настоящий ниндзя кода!"
                        });
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.BattleResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BattleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("battle_date");

                    b.Property<Guid>("BattleId")
                        .HasColumnType("uuid")
                        .HasColumnName("battle_id");

                    b.Property<long>("CompletionTime")
                        .HasColumnType("bigint")
                        .HasColumnName("completion_time");

                    b.Property<int>("ExperienceGained")
                        .HasColumnType("integer")
                        .HasColumnName("experience_gained");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("opponent_name");

                    b.Property<Guid>("ProblemSolved")
                        .HasColumnType("uuid")
                        .HasColumnName("problems_solved");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("BattleDate");

                    b.HasIndex("BattleId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("battle_results", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.RecentActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int>("ExperienceGained")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("experience_gained");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Type");

                    b.HasIndex("UserProfileId");

                    b.ToTable("recent_activities", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.RecentProblem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTime>("SolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("solved_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("Difficulty");

                    b.HasIndex("ProblemId");

                    b.HasIndex("SolvedAt");

                    b.HasIndex("UserProfileId");

                    b.ToTable("recent_problems", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.TeacherStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActiveStudents")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("active_students");

                    b.Property<double>("AverageRating")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("average_rating");

                    b.Property<int>("CreatedTasks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("created_tasks");

                    b.Property<int>("TotalSubmissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_submissions");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("teacher_stats", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid")
                        .HasColumnName("achievement_id");

                    b.Property<bool>("IsUnlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_unlocked");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress");

                    b.Property<DateTime?>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId")
                        .HasDatabaseName("ix_user_achievements_achievement");

                    b.HasIndex("IsUnlocked")
                        .HasDatabaseName("ix_user_achievements_is_unlocked");

                    b.HasIndex("UnlockedAt")
                        .HasDatabaseName("ix_user_achievements_unlocked_at")
                        .HasFilter("unlocked_at IS NOT NULL");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("ix_user_achievements_user_profile");

                    b.HasIndex("UserProfileId", "AchievementId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_achievements_user_profile_achievement");

                    b.ToTable("user_achievements", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("github_url");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("linkedin_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.HasIndex("IsPublic");

                    b.HasIndex("Level");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_user_profiles_role_teacher")
                        .HasFilter("\"Role\" = 'Teacher'");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserName");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AchievementNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("achievement_notifications");

                    b.Property<bool>("BattleInvitations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("battle_invitations");

                    b.Property<string>("CodeEditorTheme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("vs-light")
                        .HasColumnName("code_editor_theme");

                    b.Property<bool>("EmailNotifications")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("email_notifications");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("csharp")
                        .HasColumnName("preferred_language");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("light")
                        .HasColumnName("theme");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CurrentStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_streak");

                    b.Property<int>("Draws")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("draws");

                    b.Property<int>("EasyProblemsSolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("easy_problems_solved");

                    b.Property<int>("HardProblemsSolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("hard_problems_solved");

                    b.Property<int>("Losses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("losses");

                    b.Property<int>("MaxStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("max_streak");

                    b.Property<int>("MediumProblemsSolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("medium_problems_solved");

                    b.Property<string>("SolvedTaskIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuccessfulSubmissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("successful_submissions");

                    b.Property<int>("TotalBattles")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_battles");

                    b.Property<long>("TotalExecutionTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_execution_time");

                    b.Property<int>("TotalExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_experience");

                    b.Property<int>("TotalProblemsSolved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_problems_solved");

                    b.Property<int>("TotalSubmissions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_submissions");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("user_stats", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.BattleResult", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("BattleHistory")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.RecentActivity", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("RecentActivities")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.RecentProblem", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("RecentProblems")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.TeacherStats", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("TeacherStats")
                        .HasForeignKey("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.TeacherStats", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_achievements_achievements");

                    b.HasOne("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Achievements")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_achievements_user_profiles");

                    b.Navigation("Achievement");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserSettings", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("Settings")
                        .HasForeignKey("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserSettings", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserStats", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", "UserProfile")
                        .WithOne("Stats")
                        .HasForeignKey("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserStats", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("BattleHistory");

                    b.Navigation("RecentActivities");

                    b.Navigation("RecentProblems");

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Stats")
                        .IsRequired();

                    b.Navigation("TeacherStats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
