// <auto-generated />
using System;
using ByteBattlesServer.Microservices.UserProfile.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ByteBattlesServer.Microservices.UserProfile.Infrastructure.Data.Migrations
{
    [DbContext(typeof(UserProfileDbContext))]
    partial class UserProfileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_url");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("RequiredValue")
                        .HasColumnType("integer")
                        .HasColumnName("required_value");

                    b.Property<int>("RewardExperience")
                        .HasColumnType("integer")
                        .HasColumnName("reward_experience");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("RequiredValue");

                    b.HasIndex("Type");

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.BattleResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BattleDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("battle_date");

                    b.Property<Guid>("BattleId")
                        .HasColumnType("uuid")
                        .HasColumnName("battle_id");

                    b.Property<long>("CompletionTime")
                        .HasColumnType("bigint")
                        .HasColumnName("completion_time");

                    b.Property<int>("ExperienceGained")
                        .HasColumnType("integer")
                        .HasColumnName("experience_gained");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("opponent_name");

                    b.Property<int>("ProblemSolved")
                        .HasColumnType("integer")
                        .HasColumnName("problems_solved");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("BattleDate");

                    b.HasIndex("BattleId")
                        .IsUnique();

                    b.HasIndex("UserProfileId");

                    b.ToTable("battle_results", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserAchievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<Guid>("AchievementId")
                        .HasColumnType("uuid")
                        .HasColumnName("achievement_id");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserProfileId", "AchievementId")
                        .IsUnique();

                    b.ToTable("user_achievements", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bio");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GitHubUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("github_url");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("linkedin_url");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsPublic");

                    b.HasIndex("Level");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("UserName");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.BattleResult", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("BattleHistory")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserAchievement", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", "UserProfile")
                        .WithMany("Achievements")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", b =>
                {
                    b.OwnsOne("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AchievementNotifications")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("achievement_notifications");

                            b1.Property<bool>("BattleInvitations")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("battle_invitations");

                            b1.Property<string>("CodeEditorTheme")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasDefaultValue("vs-light")
                                .HasColumnName("code_editor_theme");

                            b1.Property<bool>("EmailNotifications")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("email_notifications");

                            b1.Property<string>("PreferredLanguage")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasDefaultValue("csharp")
                                .HasColumnName("preferred_language");

                            b1.Property<string>("Theme")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasDefaultValue("light")
                                .HasColumnName("theme");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_profiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserStats", "Stats", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CurrentStreak")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("current_streak");

                            b1.Property<int>("Draws")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("draws");

                            b1.Property<int>("EasyProblemsSolved")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("easy_problems_solved");

                            b1.Property<int>("HardProblemsSolved")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("hard_problems_solved");

                            b1.Property<int>("Losses")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("losses");

                            b1.Property<int>("MaxStreak")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("max_streak");

                            b1.Property<int>("MediumProblemsSolved")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("medium_problems_solved");

                            b1.Property<string>("SolvedTaskIds")
                                .HasColumnType("text")
                                .HasColumnName("solved_task_ids");

                            b1.Property<int>("SuccessfulSubmissions")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("successful_submissions");

                            b1.Property<int>("TotalBattles")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("total_battles");

                            b1.Property<long>("TotalExecutionTime")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint")
                                .HasDefaultValue(0L)
                                .HasColumnName("total_execution_time");

                            b1.Property<int>("TotalExperience")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("total_experience");

                            b1.Property<int>("TotalProblemsSolved")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("total_problems_solved");

                            b1.Property<int>("TotalSubmissions")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("total_submissions");

                            b1.Property<int>("Wins")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("wins");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("user_stats", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.UserProfile.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("BattleHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
