// <auto-generated />
using System;
using ByteBattles.Microservices.CodeBattleServer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ByteBattles.Microservices.CodeBattleServer.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ByteBattles.Microservices.CodeBattleServer.Domain.Entities.BattleRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid")
                        .HasColumnName("language_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.ToTable("battle_rooms", (string)null);
                });

            modelBuilder.Entity("ByteBattles.Microservices.CodeBattleServer.Domain.Entities.CodeSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TaskId")
                        .HasMaxLength(50)
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("code_submissions", (string)null);
                });

            modelBuilder.Entity("ByteBattles.Microservices.CodeBattleServer.Domain.Entities.BattleRoom", b =>
                {
                    b.OwnsMany("ByteBattles.Microservices.CodeBattleServer.Domain.Entities.RoomParticipant", "Participants", b1 =>
                        {
                            b1.Property<Guid>("LanguageId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("JoinedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("RoomId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("LanguageId");

                            b1.HasIndex("RoomId");

                            b1.ToTable("room_participants", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoomId");
                        });

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("ByteBattles.Microservices.CodeBattleServer.Domain.Entities.CodeSubmission", b =>
                {
                    b.HasOne("ByteBattles.Microservices.CodeBattleServer.Domain.Entities.BattleRoom", null)
                        .WithMany("Submissions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ByteBattles.Microservices.CodeBattleServer.Domain.Entities.SubmissionResult", "Result", b1 =>
                        {
                            b1.Property<Guid>("CodeSubmissionId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("ExecutionTime")
                                .HasColumnType("interval");

                            b1.Property<bool>("IsSuccess")
                                .HasColumnType("boolean");

                            b1.Property<string>("Message")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)");

                            b1.Property<int>("TestsPassed")
                                .HasColumnType("integer");

                            b1.Property<int>("TotalTests")
                                .HasColumnType("integer");

                            b1.HasKey("CodeSubmissionId");

                            b1.ToTable("code_submissions");

                            b1.WithOwner()
                                .HasForeignKey("CodeSubmissionId");
                        });

                    b.Navigation("Result");
                });

            modelBuilder.Entity("ByteBattles.Microservices.CodeBattleServer.Domain.Entities.BattleRoom", b =>
                {
                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
