// <auto-generated />
using System;
using ByteBattlesServer.Microservices.TaskServices.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ByteBattlesServer.Microservices.TaskServices.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20251021100651_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ShortTitle")
                        .IsUnique();

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InputParameters")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OutputParameters")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Difficulty");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.TaskLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdLanguage")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdTask")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdLanguage");

                    b.HasIndex("IdTask", "IdLanguage")
                        .IsUnique();

                    b.ToTable("TaskLanguages", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.TaskLanguage", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Language", "Language")
                        .WithMany("TasksLanguage")
                        .HasForeignKey("IdLanguage")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Task", "Task")
                        .WithMany("TaskLanguages")
                        .HasForeignKey("IdTask")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Language", b =>
                {
                    b.Navigation("TasksLanguage");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Task", b =>
                {
                    b.Navigation("TaskLanguages");
                });
#pragma warning restore 612, 618
        }
    }
}
