// <auto-generated />
using System;
using ByteBattlesServer.Microservices.TaskServices.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ByteBattlesServer.Microservices.TaskServices.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20251204092942_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompilerCommand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutionCommand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PatternFunction")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PatternMain")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShortTitle")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("SupportsCompilation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAd");

                    b.HasIndex("ShortTitle")
                        .IsUnique();

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("uuid");

                    b.Property<string>("NameLibrary")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAd");

                    b.HasIndex("LanguageId");

                    b.ToTable("Libraries", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("AverageExecutionTime")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PatternFunction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatternMain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReturnType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SuccessfulAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TotalAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Difficulty");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.TaskLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdLanguage")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdTask")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdLanguage");

                    b.HasIndex("IdTask", "IdLanguage")
                        .IsUnique();

                    b.ToTable("TaskLanguages", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.TaskLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdLibrary")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdTask")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdLibrary");

                    b.HasIndex("IdTask");

                    b.ToTable("TaskLibraries");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.TestCases", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsExample")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAd")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TestsTasks", (string)null);
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Library", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Language", "Language")
                        .WithMany("Libraries")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.TaskLanguage", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Language", "Language")
                        .WithMany("TasksLanguage")
                        .HasForeignKey("IdLanguage")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Task", "Task")
                        .WithMany("TaskLanguages")
                        .HasForeignKey("IdTask")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.TaskLibrary", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Library", "Library")
                        .WithMany("Libraries")
                        .HasForeignKey("IdLibrary")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Task", "Task")
                        .WithMany("Libraries")
                        .HasForeignKey("IdTask")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.TestCases", b =>
                {
                    b.HasOne("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Task", "Task")
                        .WithMany("TestCases")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Language", b =>
                {
                    b.Navigation("Libraries");

                    b.Navigation("TasksLanguage");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Library", b =>
                {
                    b.Navigation("Libraries");
                });

            modelBuilder.Entity("ByteBattlesServer.Microservices.TaskServices.Domain.Entities.Task", b =>
                {
                    b.Navigation("Libraries");

                    b.Navigation("TaskLanguages");

                    b.Navigation("TestCases");
                });
#pragma warning restore 612, 618
        }
    }
}
